// zero-vue-screen-adapter/components/ScreenAdapter.vue
<template>
  <div class="v-screen-adapter-container"
      :style="activeStyle">
    <slot></slot>
  </div>
</template>

<script setup>
import {ref, onMounted, computed, onBeforeUnmount} from 'vue';

const props = defineProps({
  designWidth: {
    type: Number,
    default: 1920, // 设计稿的宽度
  },
  designHeight: {
    type: Number,
    default: 1080, // 设计稿的高度
  },
  mode: {
    type: String,
    default: 'width', // 可选值: 'width', 'height', 'auto'
  },
});

const scale = ref(1);

const activeStyle = computed(() => ({
  transform: `scale(${scale.value}) translate(-50%, -50%)`,
  width: `${props.designWidth}px`,
  height: `${props.designHeight}px`
}));


const updateScale = () => {
  const sw =  window.innerWidth / props.designWidth;
  const sh = window.innerHeight / props.designHeight;

  scale.value = sw <   sh ? sw : sh
};

// 防抖
const debounce = (fn, t) => {
  const delay = t || 500
  let timer;
  return function() {
    const args = arguments
    if (timer) {
      clearTimeout(timer)
    }
    const context = this
    timer = setTimeout(() => {
      timer = null
      fn.apply(context, args)
    }, delay)
  }
};

const dUpdateScale = debounce(updateScale, 300);


onMounted(() => {
  updateScale();
  window.addEventListener('resize', dUpdateScale);
});

onBeforeUnmount(() => {
  window.removeEventListener('resize', dUpdateScale)
});
</script>


<style scoped>
.v-screen-adapter-container {
  transform-origin: 0 0;
  position: absolute;
  left: 50%;
  top: 50%;
  transition: 0.3s;
  background: transparent;
}
</style>

// zero-react-screen-adapter/components/ScreenAdapter.jsx
import React, { useEffect, useState } from "react";

const ScreenAdapter = ({
  mode = "fit",
  designWidth = 1920,
  designHeight = 1080,
  children,
}) => {
  const [scale, setScale] = useState(1);

  const calculateScale = () => {
    const windowWidth = window.innerWidth;
    const windowHeight = window.innerHeight;

    let newScale = 1;
    switch (mode) {
      case "width":
        newScale = windowWidth / designWidth;
        break;
      case "height":
        newScale = windowHeight / designHeight;
        break;
      case "fit":
      default:
        newScale = Math.min(
          windowWidth / designWidth,
          windowHeight / designHeight
        );
        break;
    }

    setScale(newScale);
  };

  const debounce = (fn, t) => {
    const delay = t || 500;
    let timer;
    return function () {
      const args = arguments;
      if (timer) {
        clearTimeout(timer);
      }
      const context = this;
      timer = setTimeout(() => {
        timer = null;
        fn.apply(context, args);
      }, delay);
    };
  };

  const dUpdateScale = debounce(calculateScale, 300);

  useEffect(() => {
    calculateScale();
    window.addEventListener("resize", dUpdateScale);
    return () => window.removeEventListener("resize", calculateScale);
  }, []);

  const style = {
    transform: `scale(${scale}) translate(-50%, -50%)`,
    width: `${designWidth}px`,
    height: `${designHeight}px`,
    transformOrigin: '0 0',
    position: 'absolute', 
    left: '50%',
    top: '50%',
    transition: '0.3s',
    background: 'transparent'
  };

  return <div style={style}>{children}</div>;
};

export default ScreenAdapter;
